<?xml version="1.0" encoding="utf-8"?>
<!-- ========================================================================== -->
<!-- INFININUM V2.0.0 - REPOSITORY ROOT DIRECTORY BUILD PROPS                  -->
<!-- LICENSED UNDER THE MIT LICENSE - COPYRIGHT (C) 2026 SHOCKS654              -->
<!-- ========================================================================== -->
<Project>
  <PropertyGroup>
    <Authors>Shocks654</Authors>
    <Company>InfiniNum Ecosystem</Company>
    <Product>infininum</Product>
  </PropertyGroup>
</Project>
